apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
   name: worker-cluster
   labels:
    environment: dev
spec:
   stateStoreRef:
      name: default
      kind: BucketStateStore
---
apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
   name: platform-cluster
   labels:
    environment: platform
spec:
   stateStoreRef:
      name: default
      kind: BucketStateStore